import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Router from "next/router";

type targetType = "Musics" | "Movies" | "Books" | "Games";

export default function Home() {

  const handleClick = (target: targetType) => {
    Router.push("/details/" + target);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="index">
          {/* <Card></Card> */}
          <button className="main-button" onClick={() => handleClick("Movies")}>观影生涯喜好表</button>
          <button className="main-button" onClick={() => handleClick("Musics")}>音乐生涯喜好表</button>
          <button className="main-button" onClick={() => handleClick("Games")}>游戏生涯喜好表</button>
          <button className="main-button" onClick={() => handleClick("Books")}>阅读生涯喜好表</button>
        </div>
      </main>
    </>
  );
}
