import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Index from './index'
import Router from "next/router"


export default function Home() {


	const handleMusicClick = () => {
		Router.push('/details/music');

	}
  
	const handleBookClick = () => {
	
	
  
  
	  // console.log("hans jump");
	  // Taro.navigateTo({ url: '/pages/details/music' })
	}
  
	const handleGameClick = () => {
	}
  
  
	return (
		<>
			 <Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
			
			




			<div className='index'>
				{/* <Card></Card> */}
				<button onClick={handleMusicClick}>音乐生涯喜好表</button>
				<button onClick={handleGameClick}>游戏生涯喜好表</button>
				<button id='screen' onClick={handleBookClick}>书籍生涯喜好表</button>


				<div className="share__canvas share__canvas1">
					<div className="share__canvas1-text draw_canvas" 
						data-type="text" data-text="这是一段无边距文字">
						这是一段无边距文字
					</div>
				</div>
			</div>


			</main>
		</>
		
	)
}
